{% set name = "sgp4" %}
{% set version = "2.20" %}
{% set sha256 = "9fde328872f484eb644dabe32122ba617570ff61b548b7200a9d63629ac3097c" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sgp4/sgp4-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - numpy
  imports:
    - sgp4
    - sgp4.tests
  commands:
    - python -m unittest -v sgp4.tests

about:
  home: https://github.com/brandon-rhodes/python-sgp4
  license: MIT
  license_file: {{ environ.RECIPE_DIR }}/LICENSE
  summary: Python implementation of most recent version of the SGP4 satellite tracking algorithm.

  description: |
    Python implementation of most recent version
    of the SGP4 satellite tracking algorithm.

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
