travis:
  secure:
    BINSTAR_TOKEN: NQ3ISVhpK2QUSyA583TzhOKnfp6+zaY8NdbMHC2PWhlglSBUjKacuL3Qe9ZW7OkP6FGkOJsI/RAgRz9PjGTVYZMq97kArczjVGNqv2CMzitklrCr4v4ABpPNzQAMDf9+Ug34sNX/SDB/qRjNcEYgg1WADZMih9dPmKa9ThXbrEemtk4wa9Z2e+3HM4L+XuKceXEfhyuogk41EY9At1EJkeAa7lGfPxRC9nIKYuir3MTH/XjxaRaLcm+kxrcqtSxDJZgKXvPPSQPSOyADWjHkMSkweclLV3Sw7O9xwHSzfDCI+q2UfzwosWZXvYQjog/pz+d+zQCrJq6HsAGDFCSCXnwVzkbfmF8wxxE2rZgdtgI5jVqpuMPlBn1bA5HFEVJQiK8X8Uhl3eHAKWGXkrz4WNmX+92AJ/fUtuQGYiAimOx+WNo+yYUyJtUnKRTSB4BA2fwgSfb6cJGvNX7L04LV7sFUFELIqUk77qsmRPE/VBk8PyKGtDJoCt0jnOp+eSTfrY4+Z4Xz1VmqO3/t0ifcwPjT35c5S12MOG1Uz1fJOJdHJ0ea0gsjBVwY3hArIQW8h3DHH81UKjwzZu8XnUMtrqPNZ+iKLCyvTci9CujHomEFodTqbk0mqfdgdJ6aomkwQSg46VMZYJeIxy6jhtcFLsw3h2xVmMp3sPAeFWsvc3s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
